Repository palantir/tslint, pull requests merged in 2018-11, with the labels that each got.

#4289 Includes new name Azure DevOps for VSO
  src/formatters/vsoFormatter.ts
Labels: PR: waiting for author

#4206 Added possibility to enforce different file name casings
  src/rules/fileNameCasingRule.ts
  test/rules/file-name-casing/camel-case/camelCase.ts.lint
  test/rules/file-name-casing/camel-case/no-camel-case.ts.lint
  test/rules/file-name-casing/camel-case/tslint.json
  test/rules/file-name-casing/default/tslint.json
  test/rules/file-name-casing/file-matcher/PascalCase.ts.lint
  test/rules/file-name-casing/file-matcher/camelCase.ts.lint
  test/rules/file-name-casing/file-matcher/notPascalCase.ts.lint
  test/rules/file-name-casing/file-matcher/not_camel_case.ts.lint
  test/rules/file-name-casing/file-matcher/not_kebab_case.tsx.lint
  test/rules/file-name-casing/file-matcher/tslint.json
  test/rules/file-name-casing/invalid-option/snake_case.ts.lint
  test/rules/file-name-casing/invalid-option/tslint.json
  test/rules/file-name-casing/kebab-case/kebab-case.ts.lint
  test/rules/file-name-casing/kebab-case/noKebabCase.ts.lint
  test/rules/file-name-casing/kebab-case/tslint.json
  test/rules/file-name-casing/pascal-case/PascalCase.ts.lint
  test/rules/file-name-casing/pascal-case/no-pascal-case.ts.lint
  test/rules/file-name-casing/pascal-case/tslint.json
  test/rules/file-name-casing/snake-case/no-camel-case.ts.lint
  test/rules/file-name-casing/snake-case/no-snake-case.ts.lint
Labels: PR: merge target branch, PR: waiting for reviewer

#4321 prefer-object-spread: this is new to ES2018, not ES2015
  src/rules/preferObjectSpreadRule.ts
Labels: PR: waiting for CLA
