Repository palantir/tslint, pull requests merged in 2018-12, with the labels that each got.

#4350 Use default js-yaml schema
  src/configuration.ts
  test/config/tslint-with-merge.yaml
  test/configurationTests.ts
Labels: PR: waiting for reviewer

#4352 Fix callable-types should handle `new(): T` just like `(): T`
  src/language/formatter/formatter.ts
  src/rules/callableTypesRule.ts
  test/rules/callable-types/test.ts.fix
  test/rules/callable-types/test.ts.lint
Labels: PR: waiting for author

#4323 [no-void-expression] Allow void expressions in binary expressions
  src/rules/noVoidExpressionRule.ts
  test/rules/no-void-expression/default/test.ts.lint
  test/rules/no-void-expression/ignore-arrow-function-shorthand/test.ts.lint
Labels: PR: waiting for reviewer

#4282 Changes the node version from 4 to 6 for TS 2.1 tests.
  .circleci/config.yml
Labels: PR: waiting for reviewer, Status: In Discussion

#4370 Add exception for generators in "return-undefined" rule
  src/rules/returnUndefinedRule.ts
  test/rules/return-undefined/test.ts.lint
Labels: PR: waiting for author

#4366 Use latest docs deps to avoid vulnerable libs
  docs/Gemfile.lock
Labels: PR: waiting for reviewer

#4327 Improve JUnit formatter
  src/formatters/junitFormatter.ts
  test/formatters/junitFormatterTests.ts
Labels: PR: waiting for reviewer

#4192 allow whitelisted modules to start with `@` symbol
  src/rules/noImplicitDependenciesRule.ts
  test/rules/no-implicit-dependencies/whitelist/test.ts.lint
  test/rules/no-implicit-dependencies/whitelist/tslint.json
Labels: PR: merge target branch, PR: waiting for reviewer

#4160 Badges for dependencies status
  README.md
Labels: PR: waiting for reviewer

#4034 no-invalid-this: false positive for method syntax
  src/rules/noInvalidThisRule.ts
  test/rules/no-invalid-this/enabled/test.ts.lint
Labels: PR: waiting for reviewer

#4023 [new-rule] no-default-import
  src/configs/all.ts
  src/rules/noDefaultImportRule.ts
  test/rules/no-default-import/default/test.ts.lint
  test/rules/no-default-import/default/tslint.json
  test/rules/no-default-import/fromModules/test.ts.lint
  test/rules/no-default-import/fromModules/tslint.json
Labels: PR: waiting for reviewer

#3926 import-blacklist: support banning the import of specific named exports
  src/rules/importBlacklistRule.ts
  test/rules/import-blacklist/test.ts.lint
  test/rules/import-blacklist/tslint.json
Labels: PR: waiting for reviewer

#3733 ordered-imports: check that all imports of the same type are groupped
  src/rules/orderedImportsRule.ts
  test/rules/ordered-imports/grouped-imports/test.ts.fix
  test/rules/ordered-imports/grouped-imports/test.ts.lint
Labels: PR: waiting for reviewer

#4362 Allow unknown in 'no-object-literal-type-assertion' rule.
  src/rules/noObjectLiteralTypeAssertionRule.ts
  test/rules/no-object-literal-type-assertion/test.ts.lint
Labels: PR: waiting for author

#3588 New rule: unnecessary-bind
  src/configs/all.ts
  src/rules/unnecessaryBindRule.ts
  test/rules/unnecessary-bind/typed/test.ts.lint
  test/rules/unnecessary-bind/typed/tsconfig.json
  test/rules/unnecessary-bind/typed/tslint.json
  test/rules/unnecessary-bind/untyped/test.ts.lint
  test/rules/unnecessary-bind/untyped/tslint.json
  tslint.json
Labels: PR: waiting for reviewer

#4258 Update Configuration Documentation
  docs/usage/configuration/index.md
Labels: PR: waiting for reviewer

#4193 Add object literal sort option to account for special characters
  src/rules/objectLiteralSortKeysRule.ts
  test/rules/object-literal-sort-keys/locale-compare/test.ts.lint
  test/rules/object-literal-sort-keys/locale-compare/tslint.json
Labels: PR: waiting for author, PR: waiting for reviewer

#3647 Added no-unnecessary-constructor rule
  src/configs/all.ts
  src/rules/unnecessaryConstructorRule.ts
  test/rules/unnecessary-constructor/test.ts.lint
  test/rules/unnecessary-constructor/tslint.json
Labels: PR: waiting for reviewer

#4198 Added function-constructor rule
  src/configs/all.ts
  src/configs/recommended.ts
  src/rules/code-examples/functionConstructor.examples.ts
  src/rules/functionConstructorRule.ts
  test/rules/function-constructor/test.ts.lint
  test/rules/function-constructor/tslint.json
Labels: PR: waiting for reviewer

#4274 Upgrade TSLint to support TS 3.1
  package.json
  src/language/utils.ts
  src/rules/arrayTypeRule.ts
  src/rules/arrowReturnShorthandRule.ts
  src/rules/banCommaOperatorRule.ts
  src/rules/callableTypesRule.ts
  src/rules/code-examples/functionConstructor.examples.ts
  src/rules/completed-docs/tagExclusion.ts
  src/rules/completedDocsRule.ts
  src/rules/curlyRule.ts
  src/rules/cyclomaticComplexityRule.ts
  src/rules/deprecationRule.ts
  src/rules/functionConstructorRule.ts
  src/rules/importBlacklistRule.ts
  src/rules/noAngleBracketTypeAssertionRule.ts
  src/rules/noDefaultImportRule.ts
  src/rules/noDuplicateSuperRule.ts
  src/rules/noDuplicateVariableRule.ts
  src/rules/noEmptyRule.ts
  src/rules/noInvalidThisRule.ts
  src/rules/noMagicNumbersRule.ts
  src/rules/noNullKeywordRule.ts
  src/rules/noObjectLiteralTypeAssertionRule.ts
  src/rules/noParameterReassignmentRule.ts
  src/rules/noRequireImportsRule.ts
  src/rules/noReturnAwaitRule.ts
  src/rules/noShadowedVariableRule.ts
  src/rules/noStringThrowRule.ts
  src/rules/noUnboundMethodRule.ts
  src/rules/noUnnecessaryInitializerRule.ts
  src/rules/noUnsafeAnyRule.ts
  src/rules/noUnsafeFinallyRule.ts
  src/rules/noUnusedExpressionRule.ts
  src/rules/noVarKeywordRule.ts
  src/rules/noVoidExpressionRule.ts
  src/rules/objectLiteralShorthandRule.ts
  src/rules/objectLiteralSortKeysRule.ts
  src/rules/oneLineRule.ts
  src/rules/orderedImportsRule.ts
  src/rules/preferConstRule.ts
  src/rules/preferForOfRule.ts
  src/rules/preferFunctionOverMethodRule.ts
  src/rules/preferObjectSpreadRule.ts
  src/rules/preferReadonlyRule.ts
  src/rules/quotemarkRule.ts
  src/rules/semicolonRule.ts
  src/rules/switchFinalBreakRule.ts
  src/rules/typedefRule.ts
  src/rules/unnecessaryBindRule.ts
  src/rules/variableNameRule.ts
  src/rules/whitespaceRule.ts
  src/utils.ts
  yarn.lock
Labels: PR: waiting for reviewer, Status: In Discussion

#3504 update importBlacklistRule to use regular expressions
  src/rules/importBlacklistRule.ts
  test/rules/import-blacklist/test.ts.lint
  test/rules/import-blacklist/tslint.json
Labels: PR: waiting for reviewer

#4299 Added Gitpod to third-party tools
  docs/usage/third-party-tools/index.md
Labels: PR: waiting for author
