Repository palantir/tslint, pull requests merged in 2019-03, with the labels that each got.

#4502 Added unnecessary-else Rule
  src/configs/all.ts
  src/configs/latest.ts
  src/configuration.ts
  src/formatterLoader.ts
  src/language/utils.ts
  src/language/walker/ruleWalker.ts
  src/linter.ts
  src/rules/callableTypesRule.ts
  src/rules/code-examples/unnecessaryElse.examples.ts
  src/rules/curlyRule.ts
  src/rules/noBooleanLiteralCompareRule.ts
  src/rules/noDefaultImportRule.ts
  src/rules/noInvalidThisRule.ts
  src/rules/noRestrictedGlobalsRule.ts
  src/rules/noSparseArraysRule.ts
  src/rules/noUnnecessaryQualifierRule.ts
  src/rules/noUnusedExpressionRule.ts
  src/rules/noUnusedVariableRule.ts
  src/rules/orderedImportsRule.ts
  src/rules/preferConditionalExpressionRule.ts
  src/rules/preferSwitchRule.ts
  src/rules/preferTemplateRule.ts
  src/rules/quotemarkRule.ts
  src/rules/restrictPlusOperandsRule.ts
  src/rules/returnUndefinedRule.ts
  src/rules/typeLiteralDelimiterRule.ts
  src/rules/typedefRule.ts
  src/rules/unifiedSignaturesRule.ts
  src/rules/unnecessaryElseRule.ts
  src/rules/useDefaultTypeParameterRule.ts
  src/rules/whitespaceRule.ts
  src/utils.ts
  src/verify/lines.ts
  src/verify/lintError.ts
  src/verify/parse.ts
  test/rules/unnecessary-else/test.ts.lint
  test/rules/unnecessary-else/tslint.json
Labels: PR: waiting for reviewer

#4548 Add `allow-delete` option to `no-unbound-method` rule
  src/rules/noUnboundMethodRule.ts
  test/rules/no-unbound-method/default/test.tsx.lint
  test/rules/no-unbound-method/whitelist/test.tsx.lint
  test/rules/no-unbound-method/whitelist/tslint.json
Labels: PR: waiting for author

#4543 fix for #4518: (no-trailing-whitespace) flags leading empty line as error
  src/rules/noTrailingWhitespaceRule.ts
  test/rules/no-trailing-whitespace/zero-width-no-break-space/test.ts.lint
  test/rules/no-trailing-whitespace/zero-width-no-break-space/test2.ts.lint
  test/rules/no-trailing-whitespace/zero-width-no-break-space/tslint.json
Labels: PR: waiting for author

#4546 Implement 4201: add option to ignore shadowed underscore
  src/rules/noShadowedVariableRule.ts
  test/rules/no-shadowed-variable/default/test.ts.lint
  test/rules/no-shadowed-variable/ignore-underscore/test.ts.lint
  test/rules/no-shadowed-variable/ignore-underscore/tslint.json
Labels: PR: waiting for author

#4470 Added no-tautology-expressions rule
  src/configs/all.ts
  src/rules/noTautologyExpressionRule.ts
  test/rules/no-tautology-expression/test.ts.lint
  test/rules/no-tautology-expression/tslint.json
Labels: PR: waiting for author

#2936 Added a const-only-for-caps option to variable-name
  src/configs/all.ts
  src/rules/variableNameRule.ts
  test/rules/variable-name/const-only-for-caps/test.ts.lint
  test/rules/variable-name/const-only-for-caps/tslint.json
Labels: PR: waiting for reviewer

#4521 [no-object-literal-type-assertion] New option: "allow-arguments"
  src/rules/code-examples/noObjectLiteralTypeAssertion.examples.ts
  src/rules/noObjectLiteralTypeAssertionRule.ts
  test/rules/no-object-literal-type-assertion/allow-arguments/test.ts.lint
  test/rules/no-object-literal-type-assertion/allow-arguments/tslint.json
  test/rules/no-object-literal-type-assertion/default/test.ts.lint
  test/rules/no-object-literal-type-assertion/default/tslint.json
Labels: PR: waiting for reviewer

#4492 Replace old VS Code plugin with new version
  README.md
Labels: PR: waiting for author

#4581 Added support for 'ignore-rest-args' option in 'no-any' rule
  src/rules/code-examples/noAny.examples.ts
  src/rules/noAnyRule.ts
  test/rules/no-any/default/test.ts.lint
  test/rules/no-any/default/tslint.json
  test/rules/no-any/ignore-rest-args/test.ts.lint
  test/rules/no-any/ignore-rest-args/tslint.json
Labels: PR: waiting for author

#4601 Added "fixes" to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Domain: Documentation, PR: waiting for reviewer

#4486 Handle I18n case
  src/rules/interfaceNameRule.ts
  test/rules/interface-name/always-prefix/test.ts.lint
  test/rules/interface-name/never-prefix/test.ts.lint
Labels: PR: waiting for reviewer, Status: In Discussion

#4589 Add "no-null-undefined-union" rule.
  src/configs/all.ts
  src/configuration.ts
  src/rules/noNullUndefinedUnionRule.ts
  src/rules/noUnusedVariableRule.ts
  test/rules/no-null-undefined-union/test.ts.lint
  test/rules/no-null-undefined-union/tsconfig.json
  test/rules/no-null-undefined-union/tslint.json
Labels: PR: waiting for reviewer, Type: Rule Suggestion

#4540 Fix #4530: no-string-throw fixer creates syntax errors
  src/rules/noStringThrowRule.ts
  test/rules/no-string-throw/test.ts.fix
  test/rules/no-string-throw/test.ts.lint
Labels: PR: waiting for reviewer
