Repository palantir/tslint, pull requests merged in 2019-10, with the labels that each got.

#4312 Remove some difficult recommended rules
  src/configs/recommended.ts
Labels: PR: waiting for reviewer

#4866 Used checker.getTypeArguments in return-undefined rule when possible
  src/rules/returnUndefinedRule.ts
Labels: PR: waiting for reviewer

#4533 Improve typedef for callback used as parameter
  src/rules/typedefRule.ts
  test/rules/typedef/all/test.ts.lint
  test/rules/typedef/arrow-call-signature/test.ts.lint
  test/rules/typedef/arrow-parameter/test.ts.lint
Labels: Type: Breaking Change

#4286 Add severity support for vso formatter
  src/formatters/vsoFormatter.ts
  test/formatters/vsoFormatterTests.ts
Labels: PR: waiting for reviewer, Type: Breaking Change

#2622 Don't force uppercase on ruleSeverity (#2507)
  src/language/rule/rule.ts
  test/formatters/jsonFormatterTests.ts
Labels: Type: Breaking Change

#4871 Removed annoying formatting rules from recommended ruleset
  src/configs/recommended.ts
Labels: PR: waiting for reviewer
