Repository palantir/tslint, pull requests merged in 2019-02, with the labels that each got.

#4460 add jsx-ignore option to no-magic-numbers rule
  src/rules/noMagicNumbersRule.ts
  test/rules/no-magic-numbers/allowed-numbers/test.ts.lint
  test/rules/no-magic-numbers/allowed-numbers/tslint.json
  test/rules/no-magic-numbers/default-jsx/test.tsx.lint
  test/rules/no-magic-numbers/default-jsx/tslint.json
  test/rules/no-magic-numbers/ignore-jsx/test.tsx.lint
  test/rules/no-magic-numbers/ignore-jsx/tslint.json
Labels: PR: waiting for author

#4383 Fix [ban]: wrong logic matching deeply nested methods
  src/rules/banRule.ts
  test/rules/ban/test.ts.lint
  test/rules/ban/tslint.json
Labels: PR: waiting for reviewer

#2832 Add "format" rule category
  docs/rules/index.md
  src/language/rule/rule.ts
  src/rules/alignRule.ts
  src/rules/arrowParensRule.ts
  src/rules/eoflineRule.ts
  src/rules/importSpacingRule.ts
  src/rules/indentRule.ts
  src/rules/jsdocFormatRule.ts
  src/rules/linebreakStyleRule.ts
  src/rules/maxLineLengthRule.ts
  src/rules/newParensRule.ts
  src/rules/newlineBeforeReturnRule.ts
  src/rules/noConsecutiveBlankLinesRule.ts
  src/rules/noIrregularWhitespaceRule.ts
  src/rules/noTrailingWhitespaceRule.ts
  src/rules/numberLiteralFormatRule.ts
  src/rules/quotemarkRule.ts
  src/rules/semicolonRule.ts
  src/rules/trailingCommaRule.ts
  src/rules/typedefWhitespaceRule.ts
  src/rules/whitespaceRule.ts
Labels: Formatting rule

#3824 [new-rule] no-restricted-globals
  src/configs/all.ts
  src/rules/noRestrictedGlobalsRule.ts
  test/rules/no-restricted-globals/custom-global.d.ts
  test/rules/no-restricted-globals/foo.d.ts
  test/rules/no-restricted-globals/namespace.ts.lint
  test/rules/no-restricted-globals/test.ts.lint
  test/rules/no-restricted-globals/tsconfig.json
  test/rules/no-restricted-globals/tslint.json
Labels: PR: waiting for reviewer, Requires Type Checker

#4475 Implement static-this rule (#4428)
  src/configs/all.ts
  src/language/rule/rule.ts
  src/rules/code-examples/staticThis.examples.ts
  src/rules/staticThisRule.ts
  src/rules/unifiedSignaturesRule.ts
  test/rules/static-this/test.ts.fix
  test/rules/static-this/test.ts.lint
  test/rules/static-this/tslint.json
Labels: PR: waiting for reviewer

#4524 Add option for "allow-namespace-imports" to noDuplicateImports rule
  src/rules/noDuplicateImportsRule.ts
  test/rules/no-duplicate-imports/allow-namespace-imports/test.d.ts.lint
  test/rules/no-duplicate-imports/allow-namespace-imports/test.ts.lint
  test/rules/no-duplicate-imports/allow-namespace-imports/tslint.json
  test/rules/no-duplicate-imports/default/test.d.ts.lint
  test/rules/no-duplicate-imports/default/test.ts.lint
  test/rules/no-duplicate-imports/default/test2.d.ts.lint
  test/rules/no-duplicate-imports/default/test3.d.ts.lint
  test/rules/no-duplicate-imports/default/tslint.json
  test/rules/no-duplicate-imports/tslint.json
Labels: PR: waiting for author

#4542 Documentation: fix index page to include Formatting rules
  rules/index.md
Labels: PR: waiting for reviewer
