Repository palantir/tslint, pull requests merged in 2019-06, with the labels that each got.

#4744 --print-config flag
  docs/usage/cli/index.md
  src/configuration.ts
  src/files/reading.ts
  src/files/resolution.ts
  src/runner.ts
  src/tslintCli.ts
  src/utils.ts
  test/configurationTests.ts
  test/executable/executableTests.ts
  test/files/print-config/a.ts
  test/files/print-config/b.ts
Labels: PR: waiting for reviewer

#3668 no-magic-numbers rule ignores arguments in Number prototype methods
  src/rules/noMagicNumbersRule.ts
  test/rules/no-magic-numbers/default/test.ts.lint
Labels: PR: waiting for reviewer

#3945 [New Rule] add noAsyncWithoutAwait rule
  src/configs/all.ts
  src/rules/code-examples/noAsyncWithoutAwait.examples.ts
  src/rules/noAsyncWithoutAwaitRule.ts
  test/rules/no-async-without-await/test.ts.lint
  test/rules/no-async-without-await/tslint.json
Labels: PR: waiting for reviewer

#3718 Add option to ignore accessors in adjacent-overload-signatures
  src/rules/adjacentOverloadSignaturesRule.ts
  test/rules/adjacent-overload-signatures/default/test.ts.lint
  test/rules/adjacent-overload-signatures/default/tslint.json
  test/rules/adjacent-overload-signatures/ignore-accessors/test.ts.lint
  test/rules/adjacent-overload-signatures/ignore-accessors/tslint.json
Labels: PR: merge target branch, PR: waiting for reviewer

#4519 Add strict-comparisons Rule
  src/configs/all.ts
  src/rules/code-examples/strictComparisons.examples.ts
  src/rules/strictComparisonsRule.ts
  test/rules/strict-comparisons/allow-object-equal-comparison/test.ts.lint
  test/rules/strict-comparisons/allow-object-equal-comparison/tsconfig.json
  test/rules/strict-comparisons/allow-object-equal-comparison/tslint.json
  test/rules/strict-comparisons/allow-string-order-comparison/test.ts.lint
  test/rules/strict-comparisons/allow-string-order-comparison/tsconfig.json
  test/rules/strict-comparisons/allow-string-order-comparison/tslint.json
  test/rules/strict-comparisons/default/test.ts.lint
  test/rules/strict-comparisons/default/tsconfig.json
  test/rules/strict-comparisons/default/tslint.json
  tslint.json
Labels: PR: waiting for author, Requires Type Checker

#4204 Add Exclusion Names for Rule file-name-casing
  src/rules/fileNameCasingRule.ts
  test/rules/file-name-casing/ignore/complaint.tsx.lint
  test/rules/file-name-casing/ignore/file.ts.lint
  test/rules/file-name-casing/ignore/tslint.json
Labels: PR: merge target branch, PR: waiting for reviewer

#4344 Add quotemark type validation to allow early return (#4310)
  src/rules/quotemarkRule.ts
  test/rules/quotemark/invalid-double/test.ts.fix
  test/rules/quotemark/invalid-double/test.ts.lint
  test/rules/quotemark/invalid-double/tslint.json
  test/rules/quotemark/invalid-single/test.ts.fix
  test/rules/quotemark/invalid-single/test.ts.lint
  test/rules/quotemark/invalid-single/tslint.json
Labels: PR: waiting for author

#4766 Remove .vscode/settings.json git.ignoreLimitWarning
  .vscode/settings.json
Labels: PR: waiting for reviewer
